train: False

save_dir: .

input_size: 224

#Testing config
pad_size: 4 #8
test_filepath: TMP2_x.png # #data/maddox/images/x.018.png
use_saved_model: True #If testing, whether to evaluate on random model or on pre-trained model (saved unet.h5)

#Training config
train_image_dir: data/maddox/images
train_mask_dir: data/maddox/masks
augmentation: False
validation_percentage: 0.75 # 0.2
lr: 0.001 #0.1 best for SGD
batch_size: 1
epochs: 100
optimizer_name: Adam #E.g. SGD, Adam, RMSProp
saved_model_name: unet.h5
#FIXME bring back should_augment

