train: True

save_dir: .

input_size: 224

#Testing config
pad_size: 64 #64 recommended to remove border effects on 1024 x 1024 test image
test_filepath: x.018.png #data/maddox/images/x.018.png
use_saved_model: True #If testing, whether to evaluate on random model or on pre-trained model (saved unet.h5)

#Training config
train_image_dir: data/maddox/images
train_mask_dir: data/maddox/masks
augmentation: True
dropout: True
validation_percentage: 0.2 # 0.2
lr: 0.001 #0.1 best for SGD
batch_size: 4
crop_border: 16 #Amount to crop on each side when training
epochs: 200
optimizer_name: Adam #E.g. SGD, Adam, RMSProp
saved_model_name: unet.h5

